### PR TITLE
change: Separate required and optional propTypes

### PR DESCRIPTION
**Pull request by geolessel**
As I'm thinking through more reusable Components, having the propTypes specified for each Component is helpful. But what would be super-helpful is having required and optional propTypes visually separated with the required ones on top.

Thoughts? I don't know if this is the best presentation of this idea either.

### CODE REVIEW

**Comment by rmosolgo** [comment]
:+1:

**Comment by chantastic** [comment]
I like it.

I feel like that part of the docs is already a little cluttered. I'd prefer to see it in [Using PropTypes](https://github.com/planningcenter/react-patterns#using-proptypes) or even a new section.

But I definitely like the idea of separating propTypes by reuired/optional.

**Comment by danott** [comment]
I don't see the value in this convention, but admittedly may have never run into the scenario where this would be useful.

Do you ever have optional props that do not have a corresponding entry in  `getDefaultProps`? To me, it seems like the inclusion of `isRequired` on the property in `propTypes` and the presence within `getDefaultProps` communicates it well enough?

**Comment by chantastic** [comment]
I could definitely get behind that line of thinking... The benefit of `isRequired` is mostly for the console warning in `dev`.

**Comment by geolessel** [comment]
@danott Yes, I have a component now that basically passes on optional prop through to a child. I therefore don't want to set anything in `getDefaultProps`. Now a further conversation can be had about not passing through in the first place, but until we get a good Relay implementation going, I'm not sure how to gracefully go about that.

@chantastic I like the idea of moving this to a different section though. I'll update.

**Comment by chantastic** [comment]
@geolessel I'm trying to get a better understanding of the case you had mentioned to dan. Is it possible to paste a sample or fiddle?

**Comment by geolessel** [comment]
@chantastic Sure!

I am using a single Component, [`Components.HouseholdManager.PersonSearch`](https://github.com/ministrycentered/people/blob/gl/add_proptypes_to_household_manager/app/assets/javascripts/components/household_manager/person_search.js.coffee) in two places: one where a user wants to add a Person to an existing household and one where they want to create a new household with a user. In that Component above, I have a prop called `householdId` that gets used when calling the search on the server. In the related controller, I want to exclude people from the search results if they are already in the household if I get a household id passed in. This will obviously only matter in the case of _adding a person to an already-created `Household`_. If you were creating a _new_ `Household`, there would be no household id yet.

It should probably be noted that these particular components are not using a full-on flux pattern -- they are standalone components. If they were using flux, I can see them calling on separate actions or utils or something to accomplish the distinction between having or not having a household id.

Beyond this particular case though, is it possible that a Component will check for the existence of a `prop` before deciding how to proceed? In that case as well, you'd not want to set a default and the `prop` would be optional.

**Comment by chantastic** [comment]
Could a container component add anything here? The concept in pseudo:
```js
Household => <div id={this.props.householdId} />
ExistingHousehold => <Household householdId={householdId} />
NewHousehold => <Household household=-1 />
```

**Comment by chantastic** [comment]
That way `householdId` is always an optional prop and you don't have to `getDefaultProps`

**Comment by chantastic** [comment]
but `ExistingHousehold` can have `householdId: propTypes.number.isRequired`

**Comment by geolessel** [comment]
@chantastic That is actually kinda how it is being done currently:

[`Components.HouseholdManager.AddPersonToHousehold`](https://github.com/ministrycentered/people/blob/master/app/assets/javascripts/components/household_manager/add_person_to_household.js.coffee) requires a `household_id` (yes, -1 me for inconsistent capitalization) in order to pass that on to `Components.HouseholdManager.PersonSearch`.

[`Components.HouseholdManager.CreateHousehold`](https://github.com/ministrycentered/people/blob/master/app/assets/javascripts/components/household_manager/create_household.js.coffee) does _not_ require a `household_id` but uses the `...PersonSearch` component as well. It just doesn't pass in an id.

Does that make sense? I think I'm answering/touching on your comments, but let me know if not.

**Comment by chantastic** [comment]
At the end of the day, I'm indifferent. The addition feels *pretty* nuanced.

A properly factored Components probably shouldn't be taking so many props that this type of organization is necessary, IMO.

I'll let someone else break the tie.

**Comment by danott** [comment]
The `householdId` that is passed down is for scoping people from a collection API? Is there a magic value that says don't scope to a household? Whatever the case, even setting that default prop seems like it's a big enough modifier that it should be made explicit

```coffee
# in PersonSearch
getDefaultProps: ->
  { householdId: -1 } # or other value that the actual api expects
```

**Comment by chantastic** [comment]
I'ma close this because it seems like everyone is split on this being an exemplary pattern.

**Comment by chantastic** [comment]
I'd like to examine this again? Those opposed still opposed? I was indifferent but I'm starting to feel more positively toward it.

**Pull request closed without merging**
