### PR TITLE
fix(intro) Use our preferred style in the introductory component

### PR DESCRIPTION
**Pull request by danott**
We address this specifically later on in the doc. Might be good to have it done in the same way above?

### CODE REVIEW

**Comment by chantastic** [comment]
I had left it out originally because I felt like it diluted the high-level value of this particular example. Sub-renders are somewhat contested and I wanted to keep the high-level examples somewhat opinion-free.

Is there a better way to show a simple state example that removes the need/urge for a sub-render method?

**Comment by danott** [comment]
Maybe something like 

```javascript
<Greet person="Dude Pal" />

render() {
  return <h1>Hello {this.props.person}</h1>
}
```

More explicitly - just removing the ternary operator from the mix I think leaves it clear.

**Comment by danott** [comment]
And by "the mix", i mean "the render function" :sunglasses:

**Comment by chantastic** [comment]
and not use state in the template?

**Comment by danott** [comment]
Oh yeah. Distinguishing between `state` and `props` is probably good to maintain throughout the doc. I'll open another PR if I think of a cleaner example that maintains both.

**Pull request closed without merging**
