### PR TITLE
fix compound condition

### PR DESCRIPTION
**Pull request by weblancaster**

### CODE REVIEW

**Comment by geolessel** [comment]
Good catch! Let's keep the spacing consistent, though. Can you update it to use

```javascript
return <div>{(this.isTotesHappy && "Clapping hands")}</div>;
```

**Comment by chantastic** [comment]
You could just take the parens off. They don't make much sense with the truncated example anyway.

**Comment by weblancaster** [comment]
I agree with both.. but what should it be though? I have seen the parens throughout the document. I would vote to keep.

**Comment by chantastic** [comment]
I think I might have chosen a poor example.

I tend to wrap things in parens to show where the boundaries of the conditions are. So, if the condition was longer, I'd like to see that in parens:

`{(this.state.happy && this.state.knowsIt) && "Clapping hands"}`

For the example above, this is where I'd want to see the parns:

`{(this.isTotesHappy) && "Clapping hands"}`

And at this point, I'd probably be inclined to drop the parens altogether....

But talking it through, I think you're right. In the case that this condition becomes more complex OR gets updated into a ternary, it'd be nice to already have the parens there:

`{(this.isTotesHappy) && "Clapping hands}` -> `{(this.isTotesHappy && true) && "Clapping hands"}`

`{(this.isTotesHappy) && "Clapping hands}` -> `{(this.isTotesHappy) ? "Clapping hands" : "Expressing obstinance" }`

**Comment by weblancaster** [comment]
Any update on this?

**Comment by chantastic** [comment]
@weblancaster yes, [i commented above](https://github.com/planningcenter/react-patterns/pull/24#issuecomment-138627971).

Parens around the entire expression is unnecessary and confusing. parens around the condition could make sense for ease-of-change.

If parens, it should be updated to look like this:

`{(this.isTotesHappy) && "Clapping hands}`

Otherwise they should be removed.

**Comment by geolessel** [comment]
:+1: re: @chantastic

**Comment by weblancaster** [comment]
It was updated while ago to

`{(this.isTotesHappy) && "Clapping hands"}`

**Comment by weblancaster** [comment]
Actually I had change to shorthand if

**Comment by chantastic** [comment]
Thanks!

**Comment by chantastic** [comment]
Sorry for missing the early update. That's my bad.

**Pull request merged**
