### PR TITLE
Add Flux guidelines doc

### PR DESCRIPTION
**Pull request by seven1m**
With this document, I'd like to propose some guidelines for how, when, and why to use Flux.

I don't pretend to be a React/Flux expert, but I am in a position of having implemented some Flux and feel a little like Tim "The Tool Man" Taylor: **I have found many ways *not* to do Flux.** I'm hoping to record my experiences and save others from some of tha wandering.

I would :heart: any feedback you guys may have. If anything isn't clear in this document, let me know and I'll try to clarify.

### CODE REVIEW

**Comment by chantastic** [comment]
Sweet!

I'm on my phone right now. So, I'll have to check out content later.

I think I'd like to see this as a repo of its own. I'd like to just go to the readme of a repo than a file on a repo. But I may be alone in that.

Anyone else in favor of `/planningcenter/flux-patterns` ?

**Comment by rmosolgo** [comment]
@chantastic suits me to have another repo. 

Maybe this remote week we can get heads together about how flux is applied in the different apps. For example Check-Ins looks nothing like this (because it's not really flux), but I'd be interested to hear how the other apps have implemented it. 

That would help steer towards a common approach. (Basically, I don't want to de-asynchronize Check-Ins stores unless "canonical flux" is something that we're all on board for :P)

**Comment by seven1m** [comment]
Great feedback guys.

A separate repo is fine with me.

I can't wait to put our heads together on Flux, now that we have a bit of experience with it!

**Comment by seven1m** [comment]
Closing to move to https://github.com/planningcenter/flux-patterns

**Pull request closed without merging**
