### PR TITLE
mention ES5 getters for computed props

### PR DESCRIPTION
**Pull request by capaj**
you are using ES6 string interpolation in the example, it might be beneficial to mention an ES5 solution for computed props

### CODE REVIEW

**Comment by chantastic** [comment]
Thanks for the PR!  That's a really good point. Some of these examples are a Frankensteinian blend of ES5 and ES2015.

What has your experience been with getters and `createClass`? Mine is that they bind to the prototype and not the component instance. But I could be doing something wrong.

**Comment by capaj** [comment]
@chantastic I don't know about `React.createClass` - I have been writing my apps ES6 for the past few months. In ES6
```javascript
import React from 'react';

export default class MyClass extends React.Component {
  constructor(...props) {
    super(...props);
    this.aProp; //1
    this.hasOwnProperty('aProp'); //false
  }
  get aProp(){
    return 1;
  }
}
```

So it works very well with ES6 classes.

**Comment by chantastic** [comment]
given that this is (incidentally) a Rails-related repo, I'm inclined to do make the move to ES2015-only. `react-rails` now ships with Babel by default.

**Comment by capaj** [comment]
@chantastic ES2015 is the future. I think(hope) react official docs will be soon featuring it. Most of the community seems to be doing Babel anyway.

**Comment by chantastic** [comment]
@capaj agreed. i'll ask around here and see how people feel about it. thanks for encouraging us to move this forward ;)

**Comment by chantastic** [comment]
@capaj I created a PR to update the entire README to ES6. Mind taking a look and seeing if it does a decent job of resolving this issue a little more holistically?

**Pull request closed without merging**
